# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-cero',
                'doc_host': 'https://JesusGoVar.github.io',
                'git_url': 'https://github.com/JesusGoVar/nbdev-cero',
                'lib_path': 'nbdev_cero'},
  'syms': {'nbdev_cero.core': {'nbdev_cero.core.foo': ('core.html#foo', 'nbdev_cero/core.py')}}}